import type { Application } from '@antv/li-sdk';

const config: Application = {
  version: 'v0.1',
  metadata: {
    name: '测试应用',
  },
  datasets: [
    {
      id: 'sourceId_1',
      metadata: { name: '城市温度' },
      data: [
        {
          number: 7789,
          province: '浙江省',
          city: '杭州市',
          type: '家具',
          sub_type: '桌子',
        },
        {
          number: 2367,
          province: '浙江省',
          city: '绍兴市',
          type: '家具',
          sub_type: '桌子',
        },
        {
          number: 3877,
          province: '浙江省',
          city: '宁波市',
          type: '家具',
          sub_type: '桌子',
        },
        {
          number: 4342,
          province: '浙江省',
          city: '舟山市',
          type: '家具',
          sub_type: '桌子',
        },
        {
          number: 5343,
          province: '浙江省',
          city: '杭州市',
          type: '家具',
          sub_type: '沙发',
        },
        {
          number: 632,
          province: '浙江省',
          city: '绍兴市',
          type: '家具',
          sub_type: '沙发',
        },
        {
          number: 7234,
          province: '浙江省',
          city: '宁波市',
          type: '家具',
          sub_type: '沙发',
        },
        {
          number: 834,
          province: '浙江省',
          city: '舟山市',
          type: '家具',
          sub_type: '沙发',
        },
        {
          number: 945,
          province: '浙江省',
          city: '杭州市',
          type: '办公用品',
          sub_type: '笔',
        },
        {
          number: 1304,
          province: '浙江省',
          city: '绍兴市',
          type: '办公用品',
          sub_type: '笔',
        },
        {
          number: 1145,
          province: '浙江省',
          city: '宁波市',
          type: '办公用品',
          sub_type: '笔',
        },
        {
          number: 1432,
          province: '浙江省',
          city: '舟山市',
          type: '办公用品',
          sub_type: '笔',
        },
        {
          number: 1343,
          province: '浙江省',
          city: '杭州市',
          type: '办公用品',
          sub_type: '纸张',
        },
        {
          number: 1354,
          province: '浙江省',
          city: '绍兴市',
          type: '办公用品',
          sub_type: '纸张',
        },
        {
          number: 1523,
          province: '浙江省',
          city: '宁波市',
          type: '办公用品',
          sub_type: '纸张',
        },
        {
          number: 1634,
          province: '浙江省',
          city: '舟山市',
          type: '办公用品',
          sub_type: '纸张',
        },
        {
          number: 1723,
          province: '四川省',
          city: '成都市',
          type: '家具',
          sub_type: '桌子',
        },
        {
          number: 1822,
          province: '四川省',
          city: '绵阳市',
          type: '家具',
          sub_type: '桌子',
        },
        {
          number: 1943,
          province: '四川省',
          city: '南充市',
          type: '家具',
          sub_type: '桌子',
        },
        {
          number: 2330,
          province: '四川省',
          city: '乐山市',
          type: '家具',
          sub_type: '桌子',
        },
        {
          number: 2451,
          province: '四川省',
          city: '成都市',
          type: '家具',
          sub_type: '沙发',
        },
        {
          number: 2244,
          province: '四川省',
          city: '绵阳市',
          type: '家具',
          sub_type: '沙发',
        },
        {
          number: 2333,
          province: '四川省',
          city: '南充市',
          type: '家具',
          sub_type: '沙发',
        },
        {
          number: 2445,
          province: '四川省',
          city: '乐山市',
          type: '家具',
          sub_type: '沙发',
        },
        {
          number: 2335,
          province: '四川省',
          city: '成都市',
          type: '办公用品',
          sub_type: '笔',
        },
        {
          number: 245,
          province: '四川省',
          city: '绵阳市',
          type: '办公用品',
          sub_type: '笔',
        },
        {
          number: 2457,
          province: '四川省',
          city: '南充市',
          type: '办公用品',
          sub_type: '笔',
        },
        {
          number: 2458,
          province: '四川省',
          city: '乐山市',
          type: '办公用品',
          sub_type: '笔',
        },
        {
          number: 4004,
          province: '四川省',
          city: '成都市',
          type: '办公用品',
          sub_type: '纸张',
        },
        {
          number: 3077,
          province: '四川省',
          city: '绵阳市',
          type: '办公用品',
          sub_type: '纸张',
        },
        {
          number: 3551,
          province: '四川省',
          city: '南充市',
          type: '办公用品',
          sub_type: '纸张',
        },
        {
          number: 352,
          province: '四川省',
          city: '乐山市',
          type: '办公用品',
          sub_type: '纸张',
        },
      ],
      type: 'local',
      columns: [
        {
          type: 'number',
          name: 'number',
        },
        {
          type: 'string',
          name: 'province',
        },
        {
          type: 'string',
          name: 'type',
        },
        {
          type: 'string',
          name: 'city',
        },
        {
          type: 'string',
          name: 'sub_type',
        },
      ],
    },
  ],
  spec: {
    map: {
      basemap: 'Gaode' as const,
      config: {
        zoom: 10,
        center: [120.153576, 30.287459] as [number, number],
        pitch: 0,
        bearing: 0,
        style: 'dark',
      },
    },
    layers: [],
    widgets: [
      {
        id: 'AnalysisLayout',
        type: 'AnalysisLayout',
        metadata: { name: '分析布局' },
        properties: {
          showSidePanel: true,
          showBottomPanel: false,
          showFloatPanel: false,
          collapsedFloatPanel: true,
        },
      },
      {
        id: 'SpreadSheetTable',
        type: 'SpreadSheetTable',
        metadata: { name: '表格组件' },
        properties: {
          datasetId: 'sourceId_1',
          rowHeader: ['province', 'city'],
          colHeader: ['type', 'sub_type'],
          numberValue: ['number'],
          theme: 'light',
          valueInCols: 'col',
          sheetType: 'detailedList',
          showRowSubTotals: false,
          showRowGrandTotals: true,
          showColSubTotals: false,
          showColGrandTotals: false,
        },
        container: {
          id: 'AnalysisLayout',
          slot: 'sidePanel',
        },
      },
    ],
  },
};
export default config;
